services:
  frontend:
    labels:
      - traefik.enable=true
      - traefik.http.services.${TRAEFIK_ROUTER_PREFIX:-erpnext}-frontend.loadbalancer.server.port=8080
      - traefik.http.routers.${TRAEFIK_ROUTER_PREFIX:-erpnext}-https.entrypoints=websecure
      - traefik.http.routers.${TRAEFIK_ROUTER_PREFIX:-erpnext}-https.rule=${TRAEFIK_HOST_RULE:-HostRegexp(`^.+$$`)}
      - traefik.http.routers.${TRAEFIK_ROUTER_PREFIX:-erpnext}-https.tls=true
      - traefik.http.routers.${TRAEFIK_ROUTER_PREFIX:-erpnext}-https.service=${TRAEFIK_ROUTER_PREFIX:-erpnext}-frontend

  proxy:
    image: traefik:v3.6
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.constraints=Label(`com.docker.compose.project`,`${COMPOSE_PROJECT_NAME:-erpnext}`)
      - --providers.file.directory=/traefik-config
      - --providers.file.watch=true
      - --entrypoints.websecure.address=:443
      - --log
      - --accesslog
    ports:
      - "${HTTPS_PUBLISH_PORT:-3003}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nando-deployment/certs:/certs:ro
      - ./nando-deployment/certs/traefik-tls.yml:/traefik-config/tls.yml:ro
